### ISSUE TITLE
Docker Instructions?

### ISSUE THREAD

**Issue by jakeam** [dotledger/dotledger#14]
Are there any instructions on how to set this up with Docker?

**Comment by maxguru** [comment]
I was able to use https://raw.githubusercontent.com/dotledger/dotledger/master/docker-compose.yml to get it running.

**Comment by crameth** [comment]
there's also this: https://hub.docker.com/r/dotledger/dotledger/

but so far i haven't been able to get it working (crashes whenever i try to access it)

**Comment by maxguru** [comment]
That's exactly what I am using (I am not building it).  Works perfectly for me in my Rancher setup.

```
dotledger-postgres:
  environment:
    POSTGRES_PASSWORD: dot_ledger
    POSTGRES_USER: dot_ledger
    POSTGRES_DB: dot_ledger
  tty: true
  image: postgres:9.5
  volumes:
  - dotledger-postgres-data:/var/lib/postgresql/data
  stdin_open: true
dotledger:
  ports:
  - 17080:3000/tcp
  environment:
    DATABASE_URL: postgres://dot_ledger:dot_ledger@postgres/dot_ledger?sslmode=disable
    RAILS_SERVE_STATIC_FILES: 'true'
    RAILS_LOG_TO_STDOUT: 'true'
  tty: true
  image: dotledger/dotledger
  links:
  - dotledger-postgres:postgres
  stdin_open: true
```
